# _config.yml 示例修改

title: Zijing Li's Resume
name: 李梓境 (Zijing Li)
email: l2684008188@gmail.com
description: "哈尔滨工业大学 | 具身智能 | 控制科学"

# 社交链接
social:
  github: anamazingperson
  email: l2684008188@gmail.com

# 这里的设置决定了网站的基本信息
baseurl: "" 
url: "https://anamazingperson.github.io"